name: GoldmanEssentials
main: lee.code.essentials.GoldmanEssentials
version: ${project.version}
api-version: 1.19
author: Lee
depend: [ProtocolLib, RedisCache, GoldmanCore]
softdepend: [GoldmanEnchants, Votifier]
commands:
  essreload:
    description: Reloads plugin text files.
    permission: essentials.command.reload
    usage: "/essreload"
  spawn:
    description: Teleports to server spawn.
    permission: essentials.command.spawn
    usage: "/spawn"
  setspawn:
    description: Sets the server spawn point.
    permission: essentials.command.setspawn
    usage: "/setspawn"
  gamemode:
    description: Sets your gamemode.
    permission: essentials.command.gamemode
    aliases: [gm]
    usage: "/gamemode &f<gamemode>"
  fly:
    description: Toggles your ability to fly.
    permission: essentials.command.fly
    usage: "/fly"
  flyspeed:
    description: Changes your fly speed.
    permission: essentials.command.flyspeed
    usage: "/flyspeed &f<amount>"
  world:
    description: Changes the world you're in.
    permission: essentials.command.world
    usage: "/world &f<world>"
  balance:
    description: Checks your balance.
    permission: essentials.command.balance
    aliases: [bal]
    usage: "/balance"
  balancetop:
    description: Checks the server balance leaderboard.
    permission: essentials.command.balancetop
    aliases: [baltop]
    usage: "/balancetop"
  pay:
    description: Pays another player from your balance.
    permission: essentials.command.pay
    usage: "/pay &f<player> <amount>"
  money:
    description: Changes a players balance.
    permission: essentials.command.money
    aliases: [eco]
    usage: "/money &f<set/remove/give> &f<player> <amount>"
  invsee:
    description: Opens a players inventory.
    permission: essentials.command.invsee
    usage: "/invsee &f<player>"
  enderchest:
    description: Opens a players ender chest.
    permission: essentials.command.enderchest
    aliases: [ender]
    usage: "/enderchest &f<player>"
  rankup:
    description: Rankup info and requirements.
    permission: essentials.command.rankup
    usage: "/rankup"
  setprefix:
    description: Sets a player's name prefix.
    permission: essentials.command.setprefix
    usage: "/setprefix &f<player> <prefix>"
  setsuffix:
    description: Sets a player's name suffix.
    permission: essentials.command.suffix
    usage: "/setsuffix &f<player> <suffix>"
  setcolor:
    description: Sets a player's name color.
    permission: essentials.command.setcolor
    usage: "/setcolor &f<player> <color>"
  teleport:
    description: Sends a teleport request to a player.
    permission: essentials.command.teleport
    aliases: [tp, tpa]
    usage: "/teleport &f<player>"
  back:
    description: Teleports back to your most recent saved locaiton.
    permission: essentials.command.back
    usage: "/back"
  teleportaccept:
    description: Accepts a teleport request.
    permission: essentials.command.teleportaccept
    aliases: [tpaccept]
    usage: "/teleportaccept &f<player>"
  teleportdeny:
    description: Denies a teleport request.
    permission: essentials.command.teleportdeny
    aliases: [tpdeny]
    usage: "/teleportdeny &f<player>"
  sound:
    description: Plays a sound for a player.
    permission: essentials.command.sound
    usage: "/sound &f<sound> <player>"
  glow:
    description: Toggles your player glow.
    permission: essentials.command.glow
    usage: "/glow"
  itemname:
    description: Renames the item you're holding.
    permission: essentials.command.itemname
    usage: "/itemname &f<name>"
  zap:
    description: Strikes a location or player with lightning.
    permission: essentials.command.zap
    usage: "/zap"
  advancement:
    description: Gives a player an advancement.
    permission: essentials.command.advancement
    usage: "/advancement &f<grant/revoke> <player> <advancement>"
  checkadvancement:
    description: Checks your process on a advancement.
    permission: essentials.command.checkadvancement
    usage: "/checkadvancement &f<advancement>"
  ranklist:
    description: Lists all the ranks in the server.
    permission: essentials.command.ranklist
    usage: "/ranklist"
  setrank:
    description: Sets a player's rank.
    permission: essentials.command.setrank
    usage: "/setrank &f<player> <rank>"
  summon:
    description: Spawns an entity.
    permission: essentials.command.summon
    usage: "/summon &f<entity>"
  message:
    description: Messages a online player.
    permission: essentials.command.message
    aliases: [msg, tell, whisper]
    usage: "/message &f<player> <message>"
  reply:
    description: Replies to a online player.
    permission: essentials.command.reply
    aliases: [r]
    usage: "/r &f<message>"
  enchant:
    description: Enchants the item you're holding.
    permission: essentials.command.enchant
    usage: "/enchant &f<enchant> <level>"
  heal:
    description: Gives a user full heath.
    permission: essentials.command.heal
    usage: "/heal &f<player>"
  god:
    description: Toggles being in god mode.
    permission: essentials.command.god
    usage: "/god"
  vanish:
    description: Toggles being vanished.
    permission: essentials.command.vanish
    usage: "/vanish"
  head:
    description: Gives a user a player head.
    permission: essentials.command.head
    usage: "/head &f<player>"
  feed:
    description: Feeds a user to max.
    permission: essentials.command.feed
    usage: "/feed &f<player>"
  time:
    description: Sets the time of the current world you're in.
    permission: essentials.command.time
    usage: "/time &f<setting>"
  staffchat:
    description: Toggles talking in the staff chat channel.
    permission: essentials.command.staffchat
    aliases: [sc]
    usage: "/sc &f<message>"
  give:
    description: Gives a user a item.
    permission: essentials.command.give
    usage: "/give &f<material> <player> <amount>"
  weather:
    description: Changes the weather in the world you're in.
    permission: essentials.command.weather
    usage: "/weather &f<setting>"
  help:
    description: Lists plugin info for plugins installed.
    permission: essentials.command.help
    usage: "/help"
  sell:
    description: Sells the items you're holding to the server.
    permission: essentials.command.sell
    usage: "/sell"
  sellall:
    description: Sells all of the items in your inventory of the item you're holding to the server.
    permission: essentials.command.sellall
    aliases: [sellhand]
    usage: "/sellall"
  worth:
    description: Checks the server sell worth of a item you're holding.
    permission: essentials.command.worth
    usage: "/worth"
  home:
    description: Teleports you to a saved home.
    permission: essentials.command.home
    aliases: [homes]
    usage: "/home &f<name>"
  sethome:
    description: Save a location to your home list.
    permission: essentials.command.sethome
    usage: "/sethome &f<name>"
  deletehome:
    description: Deletes a home you have saved.
    permission: essentials.command.deletehome
    aliases: [delhome]
    usage: "/deletehome &f<name>"
  ban:
    description: Bans a player from the server.
    permission: essentials.command.ban
    usage: "/ban &f<player> <reason>"
  tempban:
    description: Temporarily bans a player from the server.
    permission: essentials.command.tempban
    usage: "/tempban &f<player> <time> <reason>"
  unban:
    description: Unbans a player that has been banned.
    permission: essentials.command.unban
    usage: "/unban &f<player>"
  punished:
    description: Lists all the players that are punished.
    permission: essentials.command.punished
    aliases: [banlist]
    usage: "/punished"
  mute:
    description: Mutes a player from server chat.
    permission: essentials.command.mute
    usage: "/mute &f<player> <reason>"
  tempmute:
    description: Temporarily mutes a player from the server chat.
    permission: essentials.command.tempmute
    usage: "/tempmute &f<player> <time> <reason>"
  unmute:
    description: Unmutes a player from server chat.
    permission: essentials.command.unmute
    usage: "/unmute &f<player>"
  kick:
    description: Kicks a player from the server.
    permission: essentials.command.kick
    usage: "/kick &f<player> <reason>"
  colors:
    description: Displays all the colors that can be used in anvils, signs and books.
    permission: essentials.command.colors
    usage: "/colors"
  playtime:
    description: Checks your playtime on the server.
    permission: essentials.command.playtime
    usage: "/playtime"
  playtimetop:
    description: Checks the play time leaderboard.
    permission: essentials.command.playtimetop
    usage: "/playtimetop"
  itemlore:
    description: Changes the lore of the item you're holding.
    permission: essentials.command.itemlore
    usage: "/itemlore &f<line> <message>"
  randomteleport:
    description: Teleports you randomly in the world you're in.
    permission: essentials.command.randomteleport
    aliases: [rtp, wild]
    usage: "/randomteleport"
  rules:
    description: List of all the server rules.
    permission: essentials.command.rules
    usage: "/rules"
  addperm:
    description: Adds a permission to a player.
    permission: essentials.command.addperm
    usage: "/addperm &f<player> <perm>"
  removeperm:
    description: Removes a permission from a player.
    permission: essentials.command.removeperm
    usage: "/removeperm &f<player> <perm>"
  serversendmessage:
    description: Sends a message to any online player from the server.
    permission: essentials.command.serversendmessage
    usage: "/serversendmessage &f<player> <message>"
  namecolor:
    description: Sets your player name color.
    permission: essentials.command.namecolor
    usage: "/namecolor"
  clear:
    description: Clears a player's inventory.
    permission: essentials.command.clear
    usage: "/clear &f<player>"
  spawner:
    description: Gives a player a spawner.
    permission: essentials.command.spawner
    usage: "/spawner &f<type> <player>"
  addbooster:
    description: Adds a booster to the queue.
    permission: essentials.command.addbooster
    usage: "/addbooster &f<player> <time> <multiplier>"
  removebooster:
    description: Removes a booster from queue.
    permission: essentials.command.removebooster
    usage: "/removebooster &f<id>"
  booster:
    description: Checks booster status.
    permission: essentials.command.booster
    usage: "/booster"
  restartwarning:
    description: Restart the server.
    permission: essentials.command.restartwarning
    usage: "/restartwarning"
  motd:
    description: The server's message of the day.
    permission: essentials.command.motd
    usage: "/motd"
  resourceworlds:
    description: Opens resource world menu.
    permission: essentials.command.resourceworlds
    usage: "/resourceworlds"
  resetresourceworlds:
    description: Sets resource worlds to reset on restart.
    permission: essentials.command.resetresourceworlds
    usage: "/resetresourceworlds"
  seen:
    description: Checks the last time a player joined.
    permission: essentials.command.seen
    usage: "/seen &f<player>"
  iteminfo:
    description: Checks the data of the item you're holding.
    permission: essentials.command.iteminfo
    usage: "/iteminfo"
  afk:
    description: Sets yourself to away from keyboard.
    permission: essentials.command.afk
    usage: "/afk"
  vote:
    description: Lists server voting info.
    permission: essentials.command.vote
    usage: "/vote"
  votetop:
    description: Checks the server voting leaderboard.
    permission: essentials.command.votetop
    usage: "/votetop"
  trade:
    description: Requests to trade with another player.
    permission: essentials.command.trade
    usage: "/trade &f<player>"
  duel:
    description: Requests to pvp with another player.
    permission: essentials.command.duel
    usage: "/duel &f<player>"
  sort:
    description: Sorts containers alphabetically if you're looking at one.
    permission: essentials.command.sort
    usage: "/sort"
  bottlexp:
    description: Stores your exp in a glass bottle if you're holding one.
    permission: essentials.command.bottlexp
    usage: "/bottlexp"
    aliases: [bxp]
  emojis:
    description: List of all emojis you can use in chat, anvils, books and sings.
    permission: essentials.command.emojis
    usage: "/emojis"
  effect:
    description: Apply an effect to a target player.
    permission: essentials.command.effect
    usage: "/effect &f<player> <effect> <time>"