name: GoldmanEssentials
main: lee.code.essentials.GoldmanEssentials
version: ${project.version}
api-version: 1.16
author: Lee
depend: [ProtocolLib, RedisCache]
commands:
  spawn:
    description: Teleport to spawn.
    permission: essentials.command.spawn
  setspawn:
    description: Set the server spawn point.
    permission: essentails.command.setspawn
  gamemode:
    description: Set your gamemode.
    permission: essentails.command.gamemode
    aliases: [gm]
  fly:
    description: Toggle your ability to fly.
    permission: essentails.command.fly
  flyspeed:
    description: Change your fly speed.
    permission: essentails.command.flyspeed
  world:
    description: Change the world you're in.
    permission: essentails.command.world
  balance:
    description: Check your balance.
    permission: essentails.command.balance
    aliases: [bal]
  balancetop:
    description: Check the server balance leaderboard.
    permission: essentails.command.balancetop
    aliases: [baltop]
  money:
    description: Change a players balance.
    permission: essentails.command.money
    aliases: [eco]
  invsee:
    description: Opens a players inventory.
    permission: essentails.command.invsee
  rankup:
    description: Rankup player info.
    permission: essentails.command.rankup
  setprefix:
    description: Set a player's prefix.
    permission: essentails.command.setprefix
  setcolor:
    description: Set a player's color.
    permission: essentails.command.setcolor
  teleport:
    description: Teleport to a player.
    permission: essentails.command.teleport
    aliases: [tp]
  teleportaccept:
    description: Accept a teleport request.
    permission: essentails.command.teleport
    aliases: [tpaccept]
  teleportdeny:
    description: Deny a teleport request.
    permission: essentails.command.teleport
    aliases: [tpdeny]
  sound:
    description: Play a sound for a player.
    permission: essentails.command.sound
  glow:
    description: Toggle if you're glowing.
    permission: essentails.command.glow
  itemrename:
    description: Rename the item you're holding.
    permission: essentails.command.rename
  zap:
    description: Strike a location or player with lightning.
    permission: essentails.command.zap
  grantadvancement:
    description: Give a player an advancement.
    permission: essentails.command.grantadvancement
  revokeadvancement:
    description: Remove a player's advancement.
    permission: essentails.command.revokeadvancement
  ranklist:
    description: Lists all the ranks in the server.
    permission: essentails.command.ranklist