name: GoldmanEssentials
main: lee.code.essentials.GoldmanEssentials
version: ${project.version}
api-version: 1.16
author: Lee
depend: [ProtocolLib, RedisCache]
commands:
  spawn:
    description: Teleport to spawn.
    permission: essentials.command.spawn
  setspawn:
    description: Set the server spawn point.
    permission: essentials.command.setspawn
  gamemode:
    description: Set your gamemode.
    permission: essentials.command.gamemode
    aliases: [gm]
  fly:
    description: Toggle your ability to fly.
    permission: essentials.command.fly
  flyspeed:
    description: Change your fly speed.
    permission: essentials.command.flyspeed
  world:
    description: Change the world you're in.
    permission: essentials.command.world
  balance:
    description: Check your balance.
    permission: essentials.command.balance
    aliases: [bal]
  balancetop:
    description: Check the server balance leaderboard.
    permission: essentials.command.balancetop
    aliases: [baltop]
  money:
    description: Change a players balance.
    permission: essentials.command.money
    aliases: [eco]
  invsee:
    description: Opens a players inventory.
    permission: essentials.command.invsee
  rankup:
    description: Rankup player info.
    permission: essentials.command.rankup
  setprefix:
    description: Set a player's prefix.
    permission: essentials.command.setprefix
  setcolor:
    description: Set a player's color.
    permission: essentials.command.setcolor
  teleport:
    description: Teleport to a player.
    permission: essentials.command.teleport
    aliases: [tp]
  teleportaccept:
    description: Accept a teleport request.
    permission: essentials.command.teleportaccept
    aliases: [tpaccept]
  teleportdeny:
    description: Deny a teleport request.
    permission: essentials.command.teleportdeny
    aliases: [tpdeny]
  sound:
    description: Play a sound for a player.
    permission: essentials.command.sound
  glow:
    description: Toggle if you're glowing.
    permission: essentials.command.glow
  itemrename:
    description: Rename the item you're holding.
    permission: essentials.command.itemrename
  zap:
    description: Strike a location or player with lightning.
    permission: essentials.command.zap
  advancement:
    description: Give a player an advancement.
    permission: essentials.command.advancement
  ranklist:
    description: Lists all the ranks in the server.
    permission: essentials.command.ranklist
  setrank:
    description: Set a player's rank.
    permission: essentials.command.setrank
  summon:
    description: Spawn an entity.
    permission: essentials.command.summon
  message:
    description: Message a online player.
    permission: essentials.command.message
    aliases: [msg, tell]
  reply:
    description: Reply to a online player.
    permission: essentials.command.reply
    aliases: [r]
  enchant:
    description: Enchant the item you're holding.
    permission: essentials.command.enchant
  heal:
    description: Give yourself full health.
    permission: essentials.command.heal
  god:
    description: Toggle being in god mode.
    permission: essentials.command.god
  vanish:
    description: Toggle being vanished.
    permission: essentials.command.vanish
  head:
    description: Give yourself any player head.
    permission: essentials.command.head
  feed:
    description: Feed yourself.
    permission: essentials.command.feed
  time:
    description: Set the time of the current world you're in.
    permission: essentials.command.time
  staffchat:
    description: Talk in the staff chat channel.
    permission: essentials.command.staffchat
    aliases: [sc]