package lee.code.essentials.lists;

import lombok.AllArgsConstructor;
import lombok.Getter;
import org.bukkit.Material;
import org.bukkit.inventory.ItemStack;

@AllArgsConstructor
public enum ItemSellValues {

    BAMBOO(new ItemStack(Material.BAMBOO), 1),
    LAPIS_LAZULI(new ItemStack(Material.LAPIS_LAZULI), 2),
    REDSTONE(new ItemStack(Material.REDSTONE), 2),
    WHEAT(new ItemStack(Material.WHEAT), 2),
    FEATHER(new ItemStack(Material.FEATHER), 2),
    STRING(new ItemStack(Material.STRING), 2),
    INK_SAC(new ItemStack(Material.INK_SAC), 2),
    CARROT(new ItemStack(Material.CARROT), 3),
    GLOW_INK_SAC(new ItemStack(Material.GLOW_INK_SAC), 3),
    WHITE_WOOL(new ItemStack(Material.WHITE_WOOL), 3),
    BROWN_WOOL(new ItemStack(Material.BROWN_WOOL), 3),
    GRAY_WOOL(new ItemStack(Material.GRAY_WOOL), 3),
    BLACK_WOOL(new ItemStack(Material.BLACK_WOOL), 3),
    GUNPOWDER(new ItemStack(Material.GUNPOWDER), 3),
    BONE(new ItemStack(Material.BONE), 3),
    PHANTOM_MEMBRANE(new ItemStack(Material.PHANTOM_MEMBRANE), 3),
    BEETROOT(new ItemStack(Material.BEETROOT), 3),
    POTATO(new ItemStack(Material.POTATO), 3),
    SWEET_BERRIES(new ItemStack(Material.SWEET_BERRIES), 3),
    GLOW_BERRIES(new ItemStack(Material.GLOW_BERRIES), 3),
    SUGAR_CANE(new ItemStack(Material.SUGAR_CANE), 3),
    AMETHYST_SHARD(new ItemStack(Material.AMETHYST_SHARD), 5),
    PRISMARINE_SHARD(new ItemStack(Material.PRISMARINE_SHARD), 5),
    ENDER_PEARL(new ItemStack(Material.ENDER_PEARL), 5),
    BLAZE_ROD(new ItemStack(Material.BLAZE_ROD), 5),
    LEATHER(new ItemStack(Material.LEATHER), 5),
    RABBIT_HIDE(new ItemStack(Material.RABBIT_HIDE), 5),
    BREAD(new ItemStack(Material.BREAD), 5),
    APPLE(new ItemStack(Material.APPLE), 5),
    MELON(new ItemStack(Material.MELON), 5),
    PUMPKIN(new ItemStack(Material.PUMPKIN), 5),
    HONEYCOMB(new ItemStack(Material.HONEYCOMB), 5),
    COAL(new ItemStack(Material.COAL), 5),
    CHARCOAL(new ItemStack(Material.CHARCOAL), 5),
    NETHER_WART(new ItemStack(Material.NETHER_WART), 6),
    CAKE(new ItemStack(Material.CAKE), 10),
    PUMPKIN_PIE(new ItemStack(Material.PUMPKIN_PIE), 10),
    MAGMA_CREAM(new ItemStack(Material.MAGMA_CREAM), 10),
    SLIME_BALL(new ItemStack(Material.SLIME_BALL), 10),
    BEETROOT_SOUP(new ItemStack(Material.BEETROOT_SOUP), 10),
    MUSHROOM_STEW(new ItemStack(Material.MUSHROOM_STEW), 10),
    RABBIT_STEW(new ItemStack(Material.RABBIT_STEW), 10),
    COOKIE(new ItemStack(Material.COOKIE), 10),
    COOKED_BEEF(new ItemStack(Material.COOKED_BEEF), 10),
    COOKED_COD(new ItemStack(Material.COOKED_COD), 10),
    COOKED_SALMON(new ItemStack(Material.COOKED_SALMON), 10),
    COOKED_CHICKEN(new ItemStack(Material.COOKED_CHICKEN), 10),
    COOKED_RABBIT(new ItemStack(Material.COOKED_RABBIT), 10),
    QUARTZ(new ItemStack(Material.QUARTZ), 10),
    OBSIDIAN(new ItemStack(Material.OBSIDIAN), 15),
    CRYING_OBSIDIAN(new ItemStack(Material.CRYING_OBSIDIAN), 15),
    COPPER_INGOT(new ItemStack(Material.COPPER_INGOT), 15),
    REDSTONE_BLOCK(new ItemStack(Material.REDSTONE_BLOCK), 18),
    LAPIS_BLOCK(new ItemStack(Material.LAPIS_BLOCK), 18),
    HONEYCOMB_BLOCK(new ItemStack(Material.HONEYCOMB_BLOCK), 20),
    IRON_INGOT(new ItemStack(Material.IRON_INGOT), 20),
    HONEY_BOTTLE(new ItemStack(Material.HONEY_BOTTLE), 25),
    GOLD_INGOT(new ItemStack(Material.GOLD_INGOT), 30),
    GOLDEN_CARROT(new ItemStack(Material.GOLDEN_CARROT), 32),
    QUARTZ_BLOCK(new ItemStack(Material.QUARTZ_BLOCK), 40),
    COAL_BLOCK(new ItemStack(Material.COAL_BLOCK), 45),
    DIAMOND(new ItemStack(Material.DIAMOND), 50),
    EMERALD(new ItemStack(Material.EMERALD), 60),
    NETHERITE_INGOT(new ItemStack(Material.NETHERITE_INGOT), 70),
    NETHER_STAR(new ItemStack(Material.NETHER_STAR), 80),
    COPPER_BLOCK(new ItemStack(Material.COPPER_BLOCK), 135),
    IRON_BLOCK(new ItemStack(Material.IRON_BLOCK), 180),
    GOLDEN_APPLE(new ItemStack(Material.GOLDEN_APPLE), 250),
    GOLD_BLOCK(new ItemStack(Material.GOLD_BLOCK), 270),
    DIAMOND_BLOCK(new ItemStack(Material.DIAMOND_BLOCK), 450),
    EMERALD_BLOCK(new ItemStack(Material.EMERALD_BLOCK), 540),
    NETHERITE_BLOCK(new ItemStack(Material.NETHERITE_BLOCK), 630),
    ;

    @Getter private final ItemStack item;
    @Getter private final long value;
}
